wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1727507668.0
    t:
      1:
      - 1
      - 5
      - 11
      - 21
      - 49
      - 53
      - 55
      - 76
      - 77
      2:
      - 1
      - 5
      - 11
      - 21
      - 49
      - 53
      - 55
      - 76
      - 77
      3:
      - 2
      - 13
      - 23
      4: 3.8.18
      5: 0.16.6
      6: 4.40.1
      8:
      - 1
      - 5
      13: linux-x86_64
